### ISSUE TITLE
The title `Polymorphisms` should be changed to `Allele frequency`

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#115]
### Problem to solve

The title in the box on the variant page (/gene/2/variant/33) should be changed to `Allele frequency`.

### Further details

The title is wrong in the context on what information is shown.

### Proposal

Change the title accordingly.

### Links / references

![Screenshot 2022-07-04 at 11 36 39](https://user-images.githubusercontent.com/5663605/177127671-d9facae7-30c6-42bf-8710-a29ba3265cb6.png)

**Comment by anastasia-escher** [comment]
solved by https://github.com/SVIPdb/svip/commit/0dc1a4319df9e6edde6cb23df6bed7c02304ff4e
