### ISSUE TITLE
Add link (or button) from SVIP Summary entry to Curation entry

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#117]
### Problem to solve

From each curation entry in the SVIP summary one (if logged in) should be able to edit the curation entry directly using a link or a button

### Proposal

I suggest to put an edit button on the right of the title of add a link to the title to the appropriate curation entry. Additionally there must be the same functionality for the gene summary because this is related to the gene and not to the curation entry.

### Links / references

![Screenshot 2022-07-18 at 11 26 19](https://user-images.githubusercontent.com/5663605/179483270-fdf0c40e-2f98-4e65-a719-2958b7f51dd9.png)

**Comment by anastasia-escher** [comment]
@dameyerdave, ok!

**Comment by anastasia-escher** [comment]
@dameyerdave, would be ok like this? I think it is nicer than to put the button on the right side of the title, but it is up to you.
![ex](https://user-images.githubusercontent.com/52914023/179999741-e691d132-cc7b-4171-b3b1-174dde058f4c.png)

![ex2](https://user-images.githubusercontent.com/52914023/179999716-cf65b5da-d68e-48ca-88e0-17154ce7db9f.png)

**Comment by dameyerdave** [comment]
What about to wrap the title with an anchor where the same happens as if the button was pressed. I think it would mess up the reading experience a bit less than buttons and additional links. 
And the same must work for curation entires.

**Comment by anastasia-escher** [comment]
ok!
solved here 
https://github.com/SVIPdb/svip/commit/0e5195a13872eb93c3bd63df56a268d6ee771ddb

**Comment by anastasia-escher** [comment]
Do you find it ok, may I close the issue?

**Comment by dameyerdave** [comment]
It looks perfect! you can close the issue. Many thanks!
