### ISSUE TITLE
Add Clinical Significance and Evidence Level summary to SVIP Information

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#118]
### Problem to solve

In the `SVIP Information` table the `Clinical significance` should be a graphical representation of the different `Evidence Levels` of the curation entires.

### Further details

This is already implemented for `CIViC` public evidences and can be overtaken from there

### Proposal

Put the same components as in the `CIViC` Clinical significance and Evidence levels and put them into the `SVIP Information` table with the representation of the number of different `Evidence Types` as well as the `Evidence levels`.

### Links / references

![Screenshot 2022-07-20 at 08 22 44](https://user-images.githubusercontent.com/5663605/179912053-16df9bb0-5163-428b-86f4-21b2470425c4.png)
![Screenshot 2022-07-20 at 08 22 29](https://user-images.githubusercontent.com/5663605/179912073-e51a0246-f826-4f86-8825-17704ed00b80.png)

**Comment by dameyerdave** [comment]
A good example is https://svip-dev.nexus.ethz.ch/gene/27/variant/694

**Comment by anastasia-escher** [comment]
solved by https://github.com/SVIPdb/svip/commit/6c5573d405be3191441db1810ca97d19def414a0
