### ISSUE TITLE
Footer hised help page on mobile devices

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#119]
### Summary

Footer is too high on mobile device to display help page

### Steps to reproduce

Display the help page on a mobile device such as an iPhone.

### Example page (Optional)

https://svip-dev.nexus.ethz.ch/help

### Current *bug* behavior

One cannot see the help page on mobile device.

### Expected *correct* behavior

The help page should be displayed above the footer. Perhaps the hight properties are not set correctly for the help page container.

### Relevant screenshots and/or logs

![IMG_1C823801B29B-1](https://user-images.githubusercontent.com/5663605/179920392-f8b3c6bf-3227-473c-83eb-70328f75c2b0.jpeg)

**Comment by anastasia-escher** [comment]
solved by https://github.com/SVIPdb/svip/commit/362c417f94f9e516095436cc127bc8172576b964
