### ISSUE TITLE
Make the help page full width

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#120]
### Problem to solve

The tables on the help page need to be scrolled vertically, what is inconvenient.

### Proposal

Make the help page content fill width.

### Links / references

![Screenshot 2022-07-21 at 14 27 53](https://user-images.githubusercontent.com/5663605/180213478-caeb3b31-8cbb-4fa3-8ac2-68328c6603b8.png)

**Comment by anastasia-escher** [comment]
solved by https://github.com/SVIPdb/svip/commit/9dcb82b7398ebb2d3beb0d180d368b42b0f8d40e
