### ISSUE TITLE
Correct the help page

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#121]
### Summary

The content of the help page is not correct. Especially the tables have wrong values in wrong cells.

### Steps to reproduce

Display the help page (https://svip-dev.nexus.ethz.ch/help) and compare it with the attached PDF.

### Current *bug* behavior

The values in the table are not the same as in the PDF.

### Expected *correct* behavior

The values should be the same as on the PDF

### Relevant screenshots and/or logs

[SVIP help page.pdf](https://github.com/SVIPdb/svip/files/9159701/Annex.1.-.SVIP.help.page.pdf)

**Comment by anastasia-escher** [comment]
fixed in https://github.com/SVIPdb/svip/commit/7d407361f995e5c5c06c75ad78ebb5b682675667

**Comment by anastasia-escher** [comment]
fixed in https://github.com/SVIPdb/svip/commit/7d407361f995e5c5c06c75ad78ebb5b682675667
