### ISSUE TITLE
Test the review frontend

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#124]
### Summary

Please test and correct the review frontend/api/workflow in depth.

### Links / references

[Curation workflow.pdf](https://github.com/SVIPdb/svip/files/9198907/Curation.workflow.pdf)

**Comment by anastasia-escher** [comment]
When the variant is submitted to review, it is still possible, as a curator, to add new evidences to it. Should it be like this?

**Comment by anastasia-escher** [comment]
When the curation is complete it is shown in the "on request" table as complete, but there is still "curate" button which leads to the curation page in read-only mode (submit button is disabled there). Should the button rather be called "view" and not "curate"?
![Screenshot 2022-07-28 at 12 34 39](https://user-images.githubusercontent.com/52914023/181486319-a81295f2-e74a-4770-aa8b-592da980ee50.png)

**Comment by anastasia-escher** [comment]
1) The diagram presupposes two distinct review cycles, but in the current implementation, the steps from both are somehow merged into one review cycle. Is it meant like this? 
2) The final annotation step (if the 3 reviewers do not agree and have to discuss the issue) is not yet implemented. Should there be a separate curation table for cases like this? Like "Final annotation of the on-hold entries".  
![Screenshot 2022-07-28 at 13 06 39](https://user-images.githubusercontent.com/52914023/181491822-e6d7e714-9acc-4ebb-bd0d-7f1de0d88797.png)

**Comment by anastasia-escher** [comment]
Maybe rename "curation entries" table to "evidence entries"?
![Screenshot 2022-07-28 at 13 51 51 (2)](https://user-images.githubusercontent.com/52914023/181498599-95d6e096-c8c2-4c9a-83cb-7c0f9f74eaab.png)

**Comment by anastasia-escher** [comment]
It is possible to submit a variant for review without any evidences added. Is it a bug?

**Comment by dameyerdave** [comment]
> When the variant is submitted to review, it is still possible, as a curator, to add new evidences to it. Should it be like this?

Yes it should be like this. The implementation should somehow "flag" the curation entries that are in the review process. If the variant is submitted again only the "new" not yet curated clinical evidences need to be reviewed in a new review round. Could you check if this is the case? The curation entries that are in the review process should not be editable as long as the Reviewer have not given a negative feedback. I could be that the negative feedback includes a hint to an evidence that can be added after the negative feedback. It's like sketched out here
![Screenshot 2022-08-04 at 08 02 29](https://user-images.githubusercontent.com/5663605/182774330-b34e5629-3f3f-4511-a3d6-1ec0fc1186cf.png)

**Comment by dameyerdave** [comment]
> When the curation is complete it is shown in the "on request" table as complete, but there is still "curate" button which leads to the curation page in read-only mode (submit button is disabled there). Should the button rather be called "view" and not "curate"? ![Screenshot 2022-07-28 at 12 34 39](https://user-images.githubusercontent.com/52914023/181486319-a81295f2-e74a-4770-aa8b-592da980ee50.png)

It should be possible to curate the variant after the review but then it needs to change the status again to "Annotated" and it should go into an other round of review where only the changed curation entries have to be reviewed to get the variant into an "approved" state again. This is because there can appear new evidences for a variant over the time. Please check if this is the case.

**Comment by dameyerdave** [comment]
> It is possible to submit a variant for review without any evidences added. Is it a bug?

I don't think that make sense. It should only be submittable if there are clinical evidences in a curation entry. Because otherwise the reviewer doesn't have anything to review... So yes I thing it is a bug.

Eventually if no clinical relevant evidences were found but other evidences It can go to reviewed after submission. --> Needs to be discussed...

**Comment by dameyerdave** [comment]
> Maybe rename "curation entries" table to "evidence entries"? ![Screenshot 2022-07-28 at 13 51 51 (2)](https://user-images.githubusercontent.com/52914023/181498599-95d6e096-c8c2-4c9a-83cb-7c0f9f74eaab.png)

A curation entry is linked to one evidence. Therefor I think the name is correct. A curation entry is a classification of an evidence. And there is also the information if it is clinically relevant. And this clinically relevant evidences (curation entries) must be reviewed by a clinician.

**Comment by dameyerdave** [comment]
> 1. The diagram presupposes two distinct review cycles, but in the current implementation, the steps from both are somehow merged into one review cycle. Is it meant like this?
> 2. The final annotation step (if the 3 reviewers do not agree and have to discuss the issue) is not yet implemented. Should there be a separate curation table for cases like this? Like "Final annotation of the on-hold entries".
>    ![Screenshot 2022-07-28 at 13 06 39](https://user-images.githubusercontent.com/52914023/181491822-e6d7e714-9acc-4ebb-bd0d-7f1de0d88797.png)

This we need to discuss...

**Comment by anastasia-escher** [comment]
We have refactored the review flow so i guess this issue could be closed, @dameyerdave?

**Comment by dameyerdave** [comment]
I think so. Please close it.
