### ISSUE TITLE
Not applicable Tier level for conflicting evidences

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#125]
### Problem to solve

It can happen that evidences of the same confidence show conflicting results. In this case, their should be a value in the drop-down for  « conflicting evidence », with a selectable « not applicable » tier level ; These values should be applicable to the individual evidences but only the final variant interpretation .

### Further details

It is not yet perfectly clear how to do this, but I think you (we) find a solution.

### Proposal

During Review Workflow tests please think about this feature and come up with a possible solution.

### Links / references

[Feedback review interface 28042022.pdf](https://github.com/SVIPdb/svip/files/9198943/Feedback.review.interface.28042022.pdf)

**Comment by anastasia-escher** [comment]
Probably solved here https://github.com/SVIPdb/svip/commit/ea3f39e1372584a387fbef4bbb59f1a6c81d5a01
(But we should check if it is what was really meant)
