### ISSUE TITLE
Clean up the Reviewer Interface implementation

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#126]
### Summary

The reviewer interface / backend introduced a lot of new models (tables in the database) that are not useful because it just duplicates the relations between existing models. Therefor it's important to the rid of this unnecessary models namely
- `sibannotation1`
- `revisedreview`
- `sibannotation2`
- `curationevidence`
- `curationassociation`

The logic of the review process should be based on statuses and calculated statuses that are understandable and nicely structured.

### Further details
Please start with the  change of the model, then change the API accordingly and at the end adjust the UI components. In my opinion the visualisation of the reviewer interface is totally ok. Only the backend and model should be fixed as described.

### Proposal
We do 2 intensive sessions together on how the model and backend could be changed accordingly and then you can proceed until we have the same functionality as before but better embedded in the backend, model...
It is essential that we have a clean basis to proceed this autumn.

**Comment by anastasia-escher** [comment]
Solved in  the branch https://github.com/SVIPdb/svip/tree/restructure_api
