### ISSUE TITLE
Beautify the confirm dialogs

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#127]
### Problem to solve

Currently if you press Submit (curation entries) there is an "ugly" browser created confirm dialog. Please replace this Dialog by a VUE component.

### Further details

Generally we can always use the vue based confirm dialog instead of the browser implementation.

### Proposal

I think we already use the following component in the project: https://www.npmjs.com/package/vue-confirm-dialog. Please solve the issue by using this component.

**Comment by anastasia-escher** [comment]
Solved here https://github.com/SVIPdb/svip/commit/bb82d66f17871e1dfaa1385788cabc8f55a43c2c
