### ISSUE TITLE
"Save modification" on variant summary does not store the modified value

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#128]
### Summary

"Save modification" on variant summary does not store the modified value. This is page that follows the "Submit variant". There a curator should have the possibility to edit the variant summary a last time. But the `Save modification` button does not work and the updates are not saved.

### Steps to reproduce

1. Submit variant
2. Change the summary
3. press `Save modification`

### Example page (Optional)

.../curation/gene/237/variant/502358/submit
![Screenshot 2022-08-11 at 15 11 04](https://user-images.githubusercontent.com/5663605/184141161-3051c77a-b055-4152-aba5-eab8581f1463.png)

### Current *bug* behavior

Summary is nether saved nor there is a feedback that it is saved or not.

### Expected *correct* behavior

It should be saved and a message should be displayed saying that the summary is saved now.

**Comment by anastasia-escher** [comment]
solved in https://github.com/SVIPdb/svip/commit/a9dd59a9d0d0488316da51f3d0b8027ef22235eb
