### ISSUE TITLE
In some tables the curator name is not shown

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#129]
### Summary

In some tables the curator name is not shown

### Steps to reproduce

1. Open dashboard
2. Look at table `reviews` or `on request`
3. There is a `Curator(s)` column with no values

### Example page (Optional)

.../curation/dashboard
![Screenshot 2022-08-11 at 15 15 38](https://user-images.githubusercontent.com/5663605/184141966-086fe0da-dd03-4ac7-b8b9-299ce03658d7.png)

### Current *bug* behavior

Column `Curator(s)` has no values.

### Expected *correct* behavior

Column `Curator(s)` should be populated with the curators name abbreviation.

**Comment by anastasia-escher** [comment]
Solved in the branch https://github.com/SVIPdb/svip/tree/restructure_api
