### ISSUE TITLE
Write an email to a reviewer that agrees should be possible

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#130]
### Summary

Write an email to a reviewer that agrees should be possible

### Current *bug* behavior

In the second review cycle it is only possible to `Write email` to a reviewer that disagrees.

### Expected *correct* behavior

It should be possible to write an email to any reviewer no matter if he agrees or not.

**Comment by anastasia-escher** [comment]
Solved in https://github.com/SVIPdb/svip/commit/12b9ba1bab74bdbcbc80ad85bc632f38a69ce050
