### ISSUE TITLE
Help page PDF export

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#136]
### Problem to solve

The Help page(s) cannot be exported as a single PDF.

### Proposal

Add a button to download the whole help page as PDF.

### Links / references

svip.ch/help

**Comment by anastasia-escher** [comment]
There is a package mkdocs-pdf-export-plugin which does the job and it supports the material theme so I've changed the theme as well in https://github.com/SVIPdb/svip/commit/c2af60ba03b832a2d3706cf9ee3b111bb890abc3
