### ISSUE TITLE
Add "Save as draft" feature for reviews

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#142]
It should be possible to save the current status of the review so that the review process can be interrupted at any time. This is related to issue #143 where we want to implement the feature to immediately store changes during review, so that nothing can get lost even in a case of a computer crash.

**Comment by anastasia-escher** [comment]
solved in https://github.com/SVIPdb/svip/commit/1d42768020b6fd027cc7fbc8e49170d8ed32d73b
