### ISSUE TITLE
Save changes immediately in the  review interface 

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#143]
On any change `onChange` / `onBlur` event update the database with the new values. 
If it is simpler: you can also think about running a timer that stored the data every x seconds. 
Personally I prefer the first solution using `onChange` and `onBlur` events

**Comment by anastasia-escher** [comment]
solved in https://github.com/SVIPdb/svip/commit/659a6f785c0ec9bff5b636e0aea0652bdd6c4c8c
