### ISSUE TITLE
Fix formatting issues

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#148]
Goal: 
Every developer independent from its IDE has the same formatting of the code (prettier/eslint)

Proposal:
- Add a format command for the vue part
- Enable prettier and eslint plugins in the IDE.
- Document this on Wiki about how we do this for future projects

The format command should be something like
```
"format": "prettier --write . && npx eslint --ext .js,.vue --ignore-path .gitignore --fix"
```

**Comment by anastasia-escher** [comment]
Solved here https://github.com/SVIPdb/svip/wiki/Formatting
and here https://github.com/SVIPdb/svip/commit/a955d0dd419e08f52c946315dfe4af26e58467bc
