### ISSUE TITLE
Extend platform links to link directly to the variant

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#150]
### Problem to solve

At the moment the platform links are  not directly linked to the particular variant. 

### Further details

It would be nice to directly link to the particular variant

### Proposal

Add the variant specification somehow to the link so that the particular variant is directly shown on the platform

### Links / references

<img width="2033" alt="Screenshot 2022-09-14 at 09 57 30" src="https://user-images.githubusercontent.com/5663605/190096716-157e13d1-003b-4a2d-9705-b9a94dead560.png">

**Comment by anastasia-escher** [comment]
Solved here https://github.com/SVIPdb/svip/commit/828fd1e3c109d17fa9b7b873c70799c3412166fd
Except for the cases with a sortable table: https://github.com/SVIPdb/svip/issues/151#issue-1378127941
