### ISSUE TITLE
Update About page

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#159]
We need to update the About page:
- Under **Events** we need to add the events since 2019 - details will follow
- We need to remove the **Stay tunes** section

**Comment by dameyerdave** [comment]
Here some events to add:
- Cancer Genomics Consortium annual meeting, St Louis, MI, USA (01-03 August 2022)
- BioTechX congress, Basel, Switzerland (08-10 November 2022)

**Comment by anastasia-escher** [comment]
solved in https://github.com/SVIPdb/svip/commit/3e85f16c39b8326079bcb2855e184605511935a4
