### ISSUE TITLE
Check duplications in curation entries list in SVIP information

### ISSUE THREAD

**Issue by dameyerdave** [SVIPdb/coordinator#160]
In the list of curations I recognised that there are sone duplications. I don't think that's correct. Could you please check and resolve this.

![Screenshot 2022-11-07 at 13 39 08](https://user-images.githubusercontent.com/5663605/200313253-11444df1-21e7-4d07-8b2e-017ff5536bd9.png)

**Comment by anastasia-escher** [comment]
All these items have different id's, so they must have been made with the option "duplicate evidence" (so they have the same content but these are separate items in the DB). 

![Screenshot 2022-12-20 at 15 54 36](https://user-images.githubusercontent.com/52914023/208696404-84eecda6-a615-489d-842f-b998b915b05f.png)
